### ISSUE TITLE
Patch required?

### ISSUE THREAD

**Issue by jsumners** [javiplx/ansible-library#14]
The readme mentions a patch to `ansible-galaxy` is required to make it work with this server. Is that still necessary? Is it not enough to specify the server URL in `ansible.cfg`? If it is still required, what are the details about how to make the patch?

**Comment by javiplx** [comment]
I though that the patch was linked in the documentation, so I'll modify that. In the meantime, it is at https://github.com/ansible/ansible/pull/14779/files. As you ask for the server config parameter, I guess you are using ansible 2.x, and that patch is the right one. For ansible 1.9 a slightly larger patch (that I'm not able to find now) is required, to add the server param to ansible.cfg.

**Comment by javiplx** [comment]
I've remembered where the full patch for ansible 1.9 was, at https://github.com/Feverup/ansible/pull/1/files

**Comment by javiplx** [comment]
The patch should not be required anymore. The ansible people accepted a change similar to the one I proposed, and I've modified ansible-library to fit, so that can be used with recent stock ansible releases
